[package]
name = "ambi"
version = "0.2.5"
edition = "2021"
description = "A flexible, multi-backend, customizable AI agent framework, entirely based on Rust."
license = "Apache-2.0"
repository = "https://github.com/Maskviva/Ambi"
readme = "README.md"
keywords = ["ai", "agent", "llm", "llama", "openai"]
categories = [
    "artificial-intelligence",
    "api-bindings",
    "asynchronous"
]

[lib]
name = "ambi"
path = "src/lib.rs"

[features]
default = ["openai-api"]

llama-cpp = ["dep:llama-cpp-2", "dep:llama-cpp-sys-2"]
openai-api = ["dep:async-openai"]

mtmd = ["llama-cpp", "llama-cpp-2/mtmd", "llama-cpp-sys-2/mtmd"]
cuda = ["llama-cpp", "llama-cpp-2/cuda", "llama-cpp-sys-2/cuda"]
vulkan = ["llama-cpp", "llama-cpp-2/vulkan", "llama-cpp-sys-2/vulkan"]
metal = ["llama-cpp", "llama-cpp-2/metal", "llama-cpp-sys-2/metal"]
rocm = ["llama-cpp", "llama-cpp-2/rocm", "llama-cpp-sys-2/rocm"]

[dependencies]
log = "0.4"
thiserror = "2.0.18"
llama-cpp-2 = { version = "0.1.145", optional = true }
llama-cpp-sys-2 = { version = "0.1.145", optional = true }
async-openai = { version = "0.36.0", features = ["full"], optional = true }

serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.149"
tokio = { version = "1.52.1", features = ["full"] }
tokio-stream = "0.1.18"
async-trait = "0.1.89"
anyhow = "1.0.102"
futures = "0.3.32"
tiktoken-rs = "0.11.0"
base64 = "0.22.1"

[dev-dependencies]
chrono = "0.4"

[[example]]
name = "chat_local"
required-features = ["llama-cpp"]

[[example]]
name = "chat_cloud"
required-features = ["openai-api"]

[[example]]
name = "custom_tool"
required-features = ["openai-api"]

[[example]]
name = "custom_model_back"