/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Agent {
  static make(config: JsLLMEngineConfig): Promise<Agent>
  preamble(text: string): Agent
  template(templateType: JsChatTemplateType): Agent
  customTemplate(template: JsChatTemplate): Agent
  withEvictionStrategy(strategy: JsEvictionStrategy): Agent
  maxIterations(n: number): Agent
  withStandardFormatting(): Agent
  tool(name: string, description: string, parameters_json_str: string, callback: (_err: Error | null, argsJson: string) => string, timeoutSecs?: number, maxRetries?: number, isIdempotent?: boolean): Agent
  withToolTags(startTag: string, endTag: string): Agent
  countTokens(text: string): number
  onEvict(callback: (arg?: unknown) => unknown): Agent
}
export type JsAgent = Agent

export declare class AgentState {
  constructor(sessionId: string)
  get sessionId(): Promise<string>
  getDynamicContext(): Promise<string>
  setDynamicContext(context: string): Promise<void>
  appendDynamicContext(context: string): Promise<void>
  clearDynamicContext(): Promise<void>
  clearHistory(agent: Agent): Promise<void>
  historyLen(): Promise<number>
  historyIsEmpty(): Promise<boolean>
  historyAll(): Promise<Array<JsMessage>>
  historySearchByKeyword(keyword: string): Promise<Array<JsMessage>>
  lastUserMessage(): Promise<JsMessage | null>
  lastAssistantMessage(): Promise<JsMessage | null>
  historyTruncate(len: number): Promise<void>
  historyTotalTokens(): Promise<number>
  fork(): Promise<AgentState>
}
export type JsAgentState = AgentState

export declare class ChatStream {
  nextChunk(): Promise<string | null>
}
export type JsChatStream = ChatStream

export declare class LLMEngineConfig {
  static openai(config: JsOpenAiEngineConfig): LLMEngineConfig
  static custom(chatHandler: (_err: Error | null, argsJson: string) => void, supportsMultimodal?: boolean, chatStreamHandler?: (_err: Error | null, argsJson: string) => void): LLMEngineConfig
}
export type JsLLMEngineConfig = LLMEngineConfig

export declare class Pipeline {
  static chatRunner(maxConcurrency?: number | undefined | null): Pipeline
  static custom(executeHandler: (_err: Error | null, argsJson: string) => void, streamHandler?: (_err: Error | null, argsJson: string) => void): Pipeline
  chat(agent: Agent, state: JsAgentState, prompt: string): Promise<string>
  execute(agent: Agent, state: JsAgentState, input: Array<any>): Promise<string>
  executeParts(agent: Agent, state: JsAgentState, input: Array<JsContentPart>): Promise<string>
  chatStream(agent: Agent, state: JsAgentState, prompt: string): Promise<JsChatStream>
  static clearHistory(agent: Agent, state: JsAgentState): Promise<void>
}
export type JsPipeline = Pipeline

export declare function chatmlTemplate(): JsChatTemplate

export declare function deepseekTemplate(): JsChatTemplate

export declare function gemmaTemplate(): JsChatTemplate

export interface JsChatTemplate {
  systemPrefix: string
  systemSuffix: string
  userPrefix: string
  userSuffix: string
  assistantPrefix: string
  assistantSuffix: string
  thinkPrefix: string
  thinkSuffix: string
  toolPrefix: string
  toolSuffix: string
  toolIdPrefix: string
  toolIdSuffix: string
  mediaPlaceholder: string
}

export declare const enum JsChatTemplateType {
  Chatml = 0,
  Llama3 = 1,
  Gemma = 2,
  Phi3 = 3,
  Zephyr = 4,
  Deepseek = 5,
  Qwen = 6,
  Mistral = 7,
  Llama2 = 8
}

export interface JsContentPart {
  type: string
  text?: string
  base64?: string
}

export interface JsEvictionStrategy {
  maxSafeTokens: number
}

export interface JsMessage {
  role: string
  content: string
  toolCalls?: Array<JsToolCall>
  toolId?: string
  parts?: Array<JsContentPart>
}

export interface JsOpenAiEngineConfig {
  apiKey: string
  modelName: string
  baseUrl?: string
  temp?: number
  topP?: number
}

export interface JsToolCall {
  name: string
  arguments: string
  id: string
}

export declare function llama2Template(): JsChatTemplate

export declare function llama3Template(): JsChatTemplate

export declare function mistralTemplate(): JsChatTemplate

export declare function phi3Template(): JsChatTemplate

export declare function qwenTemplate(): JsChatTemplate

/** Called from JS when an async pipeline callback finishes. */
export declare function resolvePipelineRequest(requestId: string, result: string): void

/** Called from JS when an async LLM callback finishes. */
export declare function resolveRequest(requestId: string, result: string): void

export declare function zephyrTemplate(): JsChatTemplate
