[package]
name = "ambi-macros"
version = "0.1.1"
edition = "2021"
description = "Procedural macros for Ambi"
license = "Apache-2.0"
repository = "https://github.com/Maskviva/Ambi"
readme = "README.md"

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"